# Generated by Django 2.2.16 on 2022-01-17 09:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["-id"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.RemoveField(
            model_name="title",
            name="rating",
        ),
        migrations.AddField(
            model_name="title",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="title",
            name="genre",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="genre",
                to="reviews.Genre",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=20, verbose_name="Категория"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                max_length=10, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="title",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_title",
                to="reviews.Category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="name",
            field=models.CharField(
                max_length=20, verbose_name="Название произведения"
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.PositiveIntegerField(
                db_index=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(2022),
                ],
                verbose_name="Год",
            ),
        ),
    ]
