# Generated by Django 2.2.16 on 2022-01-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_auto_20220120_0931"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-id"],
                "verbose_name": "Отзыв",
                "verbose_name_plural": "ОТзыв",
            },
        ),
        migrations.AlterModelOptions(
            name="title",
            options={"ordering": ["-id"]},
        ),
    ]
